# GDAL GTiff default creation options
gdal_creation_options   : [ "COMPRESS=LZW", "PREDICTOR=2",
                            "BIGTIFF=YES", "TILED=YES",
                            "BLOCKXSIZE=512", "BLOCKYSIZE=512" ]

gdalcubes_options       : ["COMPRESS=LZW", "PREDICTOR=2",
                           "BIGTIFF=YES", "BLOCKXSIZE=512",
                           "BLOCKYSIZE=512"]

# maxbytes per plot (in MB)
plot_max_Mbytes: 10
# tmap max_cells (in number of cells)
tmap_max_cells: 1e+06
# tmap configuration parameters
tmap_graticules_labels_size: 0.7
tmap_legend_title_size: 1.5
tmap_legend_text_size: 1.2
tmap_legend_bg_color: "white"
tmap_legend_bg_alpha: 0.5

# maxbytes for leaflet (in MB)
leaflet_max_megabytes : 64
# estimated compression factor for leaflet
leaflet_comp_factor : 0.50
