# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bayes_smoother_fraction <- function(logits, nrows, ncols, window_size, smoothness, neigh_fraction) {
    .Call(`_bayesEO_bayes_smoother_fraction`, logits, nrows, ncols, window_size, smoothness, neigh_fraction)
}

bayes_var <- function(m, m_nrow, m_ncol, w, neigh_fraction) {
    .Call(`_bayesEO_bayes_var`, m, m_nrow, m_ncol, w, neigh_fraction)
}

C_label_max_prob <- function(x) {
    .Call(`_bayesEO_C_label_max_prob`, x)
}

